# Generated by Django 6.0.4 on 2026-04-13 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('total_harga', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dibayar', 'Dibayar')], default='pending', max_length=10)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='produk/')),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.pesanan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.produk')),
            ],
        ),
    ]
