# Generated by Django 4.2.7 on 2026-04-13 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempesanan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('verifikasi', 'Menunggu Verifikasi'), ('dibayar', 'Sudah Dibayar'), ('dikemas', 'Sedang Dikemas'), ('dikirim', 'Sedang Dikirim'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='pending', max_length=20)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti/')),
                ('resi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
