# Generated by Django 5.2.4 on 2026-04-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempesanan',
            name='harga_satuan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='id_pesanan',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='diskon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produk',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(choices=[('celana', 'Celana Jeans'), ('jaket', 'Jaket Denim'), ('kaos', 'Kaos Denim'), ('aksesoris', 'Aksesoris Denim')], default='celana', max_length=20),
        ),
        migrations.AlterField(
            model_name='itempesanan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itempesanan',
            name='pesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toko.pesanan'),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dibayar', 'Dibayar'), ('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
