# Generated by Django 5.2.4 on 2026-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_produk_gambar2_produk_gambar3_produk_gambar4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='metode_pembayaran',
            field=models.CharField(choices=[('qris', 'QRIS'), ('transfer', 'Transfer Bank')], default='qris', max_length=10),
        ),
    ]
